<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChaoticKit.VirtualFileSystem\ChaoticKit.VirtualFileSystem.csproj" />
    <ProjectReference Include="..\ChaoticKit\ChaoticKit.csproj" />
  </ItemGroup>

</Project>
